-- Brainwalk Database Schema for Supabase
-- Run this in your Supabase SQL Editor to set up the database

-- Create content table
CREATE TABLE IF NOT EXISTS content (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  preview TEXT NOT NULL,
  full_content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable Row Level Security
ALTER TABLE content ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON content
  FOR SELECT USING (true);

-- Create policy to allow insert for authenticated users (optional, for future admin panel)
CREATE POLICY "Allow authenticated insert" ON content
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create index on category for faster filtering
CREATE INDEX IF NOT EXISTS idx_content_category ON content(category);

-- Insert sample content
INSERT INTO content (category, title, preview, full_content) VALUES
  -- 15th century poetry
  ('15th century poetry', 'The Ballad of Lost Gardens', 'In chambers old where shadows play, a voice speaks soft of yesterday. The ink runs thin, the parchment worn...', 'In chambers old where shadows play, a voice speaks soft of yesterday. The ink runs thin, the parchment worn, yet verses live from ages born.\n\nThe gardens lost to time and tide, where lovers walked side by side, now sleep beneath the winter snow, their stories only poets know.\n\nThe words that danced on candlelight, now whisper through the endless night, a reminder that beauty fades, but art endures through all decades.'),

  ('15th century poetry', 'Ode to the Wandering Moon', 'Silver coin upon the velvet night, guiding travelers with gentle light. The moon has seen empires rise and fall...', 'Silver coin upon the velvet night, guiding travelers with gentle light. The moon has seen empires rise and fall, witnessed kings and peasants, one and all.\n\nShe watches from her throne of stars, healing earth''s invisible scars, constant in her changing face, teaching mortals time and grace.\n\nO wandering moon, eternal guide, who keeps the secrets oceans hide, your silent wisdom lights the way for those who dare to go astray.'),

  -- 1600s history
  ('1600s history', 'The Tulip Mania of 1637', 'In the Dutch Golden Age, tulip bulbs became more valuable than houses. At its peak, a single bulb could cost ten times a craftsman''s annual wage...', 'In the Dutch Golden Age, tulip bulbs became more valuable than houses. At its peak, a single bulb could cost ten times a craftsman''s annual wage. This speculative bubble, known as Tulip Mania, represents one of history''s first recorded economic bubbles.\n\nThe craze began when tulips were introduced to the Netherlands from Turkey. Their vibrant colors and unique patterns made them status symbols among the wealthy. Soon, a futures market developed where bulbs were traded before they even bloomed.\n\nWhen the bubble burst in February 1637, fortunes evaporated overnight. The crash sent shockwaves through Dutch society and serves as an early lesson in the dangers of speculative excess and market psychology.'),

  ('1600s history', 'The Great Fire of London', 'On September 2nd, 1666, a small fire in a bakery on Pudding Lane would grow to consume four-fifths of London. The inferno burned for four days...', 'On September 2nd, 1666, a small fire in a bakery on Pudding Lane would grow to consume four-fifths of London. The inferno burned for four days, destroying over 13,000 houses and 87 churches, including the original St. Paul''s Cathedral.\n\nThe medieval city, with its closely-packed timber buildings and narrow streets, was a tinderbox waiting to ignite. Strong winds spread the flames rapidly, and firefighting efforts were hampered by outdated equipment and bureaucratic delays.\n\nIronically, the disaster led to London''s rebirth. Sir Christopher Wren redesigned much of the city, implementing wider streets, better building codes, and architectural innovations. The modern London we know today rose from these ashes, transforming from a medieval warren into a planned metropolis.'),

  -- Tech news
  ('tech news', 'The Rise of Rust in System Programming', 'Rust has quietly become the darling of system programmers, offering memory safety without garbage collection. Major tech companies are adopting it...', 'Rust has quietly become the darling of system programmers, offering memory safety without garbage collection. Major tech companies including Microsoft, Amazon, and Google are adopting it for critical infrastructure.\n\nWhat makes Rust special is its ownership system—a compile-time guarantee that prevents common bugs like null pointers and data races. This means you get C-like performance with Python-like safety.\n\nThe Linux kernel recently accepted its first Rust code, marking a historic shift for a project written exclusively in C for three decades. As software security becomes paramount, Rust''s "if it compiles, it probably works" philosophy is winning converts across the industry.'),

  ('tech news', 'Quantum Computing Reaches Practical Milestone', 'IBM and Google have demonstrated quantum computers solving problems beyond classical capabilities. We''re entering the "quantum advantage" era...', 'IBM and Google have demonstrated quantum computers solving problems beyond classical capabilities. We''re entering the "quantum advantage" era, where certain calculations become practically impossible for traditional computers.\n\nQuantum computers exploit superposition and entanglement to process information in fundamentally new ways. A quantum bit can be both 0 and 1 simultaneously, allowing parallel computation at unprecedented scales.\n\nThe implications span cryptography, drug discovery, and climate modeling. While we''re years from desktop quantum computers, cloud-based quantum services are already available. The race is on to develop quantum-resistant encryption before these machines can break today''s security standards.'),

  -- Short stories
  ('short stories', 'The Last Librarian', 'In the year 2087, books were memories. Elena was the last person on Earth who remembered the smell of paper, the weight of a hardcover in her hands...', 'In the year 2087, books were memories. Elena was the last person on Earth who remembered the smell of paper, the weight of a hardcover in her hands.\n\nThe Great Digitization had swept through like wildfire, promising infinite access and zero waste. Libraries became data centers. Reading became scrolling. And somehow, in the translation, something essential was lost.\n\nElena descended into her basement every evening, where she kept her collection—three hundred physical books, contraband in an age of infinite streams. She would run her fingers along their spines, select one at random, and lose herself in pages that crinkled with age.\n\nOne day, a child knocked on her door. "My grandmother told me you have... books?" The word sounded foreign in the girl''s mouth. Elena smiled. Perhaps she wasn''t the last after all.'),

  ('short stories', 'Coffee at Midnight', 'The diner existed in a fold between moments, appearing only to those who needed it most. Marcus found it on the worst night of his life...', 'The diner existed in a fold between moments, appearing only to those who needed it most. Marcus found it on the worst night of his life, walking aimlessly through rain-soaked streets at midnight.\n\nInside, warmth enveloped him. A waitress with kind eyes poured coffee without asking. Around him sat others—each at their own table, each lost in their own despair.\n\nHe stayed until dawn, watching the other patrons slowly stand, straighten their shoulders, and walk back into the world with something restored in their eyes. When he finally left, Marcus glanced back. The diner was gone, leaving only an empty lot.\n\nBut the coffee''s warmth remained, and with it, the knowledge that even in our darkest moments, the universe conspires to remind us we''re not alone.'),

  -- Philosophy
  ('philosophy', 'The Paradox of Choice', 'More options should mean more freedom, yet studies show that abundance of choice often paralyzes us. Barry Schwartz calls this the "tyranny of choice"...', 'More options should mean more freedom, yet studies show that abundance of choice often paralyzes us. Barry Schwartz calls this the "tyranny of choice"—when limitless options breed anxiety rather than liberation.\n\nConsider streaming services: thousands of films available, yet we spend 20 minutes scrolling before watching nothing. Or online dating: unlimited potential matches, yet we''re less committed because someone "better" might be one swipe away.\n\nThe paradox reveals a deeper truth: freedom isn''t just about having options—it''s about having the wisdom to choose. Constraints can be liberating. A painter with three colors may create more meaningful art than one with three hundred, because limitations force intention.\n\nPerhaps the path to satisfaction isn''t maximizing choice, but learning to be satisfied with "good enough."'),

  ('philosophy', 'The Ship of Theseus in Modern Life', 'If you replace every plank of a ship, is it still the same ship? This ancient paradox has new relevance in our age of continuous self-optimization...', 'If you replace every plank of a ship, is it still the same ship? This ancient paradox has new relevance in our age of continuous self-optimization.\n\nEvery cell in your body replaces itself over time. Your thoughts evolve. Your values shift. The "you" of today shares little physical matter with the "you" of ten years ago. So what makes you, you?\n\nWe''re constantly rebuilding ourselves—new habits, new beliefs, new bodies through diet and exercise. Social media shows us curated versions of others who seem to have upgraded successfully. The pressure to optimize is relentless.\n\nBut perhaps continuity isn''t about unchanging substances, but about the pattern that persists through change. You are not a static object but a dynamic process, a story being written. The question isn''t whether you''re the same ship, but whether you''re steering toward your chosen destination.'),

  -- Science
  ('science', 'Octopuses: Alien Intelligence on Earth', 'With nine brains and three hearts, octopuses represent an intelligence completely unlike our own. Their neurons are distributed throughout their arms...', 'With nine brains and three hearts, octopuses represent an intelligence completely unlike our own. Their neurons are distributed throughout their arms, which can taste what they touch and solve problems independently.\n\nUnlike humans, whose intelligence evolved from social cooperation, octopuses are solitary. They don''t learn from parents or pass down culture. Each octopus reinvents the wheel, yet they''ve been observed using tools, solving complex puzzles, and even displaying what appears to be playfulness.\n\nTheir cognitive architecture is so different from ours that studying them offers insights into what intelligence itself really means. If we ever encounter alien life, it might think more like an octopus than like us—distributed, decentralized, fundamentally strange.\n\nThese creatures remind us that consciousness isn''t a single phenomenon but a spectrum of solutions to the problem of existing in a complex world.'),

  ('science', 'The Mysterious Microbiome Within', 'You are not alone in your own body. Trillions of microorganisms live in your gut, outnumbering your human cells. They''re not just passengers—they''re active participants...', 'You are not alone in your own body. Trillions of microorganisms live in your gut, outnumbering your human cells. They''re not just passengers—they''re active participants in your health, mood, and even decision-making.\n\nResearch shows that gut bacteria produce neurotransmitters like serotonin and dopamine. They communicate with your brain via the vagus nerve, influencing everything from anxiety levels to food cravings. Some scientists argue you don''t have a microbiome—you are a microbiome.\n\nThis ecosystem can be disrupted by antibiotics, diet, and stress, potentially contributing to depression, obesity, and autoimmune diseases. But it can also be cultivated: fermented foods, fiber, and even specific bacterial supplements can shift the balance.\n\nWe''re learning that health isn''t about the individual human body, but about the complex ecological community that we host. Taking care of yourself means taking care of your trillion invisible partners.');
